server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

wx:
  url:
    getPhoneNumber: http://api.weixin.qq.com/wxa/business/getuserphonenumber
    subscribeMessage: http://api.weixin.qq.com/cgi-bin/message/subscribe/send
    beforeUploadFile: https://api.weixin.qq.com/tcb/uploadfile
  message:
    template:
      bookedsuccess:
        id: S8NGsSZ3iWDXUc-6xgS50SJNYeRbZ9p-03PjV_62dlU
      bookedcancel:
        id: yqdMTsUoHYEK6HuxHcmTx9xSY0sWGgJthQYCFPBFCDU

  env: ${ENV_ID}
  mch: ${MCH_ID}


pay:
  orderquery:
    url: http://api.weixin.qq.com/_/pay/orderquery
  unifiedOrder:
    url: http://api.weixin.qq.com/_/pay/unifiedOrder
    callback:
      service: ${CALLBACK_SERVICE}
      path: /pay/callback

sercurity:
    algorithm: SHA256withRSA
